blank_issues_enabled: false
contact_links:
  - name: Question générale
    url: https://github.com/AmauryCESIZen/cesizen-web/discussions
    about: Pour une question qui n'est ni un bug ni une demande d'évolution.
